# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-05 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Jabatan'),
        ),
    ]
