# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-11 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import overtime.apps.users.models
import overtime.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=254, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, verbose_name=b'Nama')),
                ('no_file', models.CharField(blank=True, max_length=255, verbose_name=b'No File')),
                ('mobile_number', models.CharField(blank=True, max_length=30, null=True, unique=True, validators=[overtime.core.validators.validate_mobile_phone], verbose_name=b'Nomor Ponsel')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, b'Admin'), (2, b'User'), (3, b'Coordinator'), (4, b'Manager')], default=2)),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Jabatan')),
                ('department', models.PositiveSmallIntegerField(blank=True, choices=[(1, b'Teknas'), (2, b'Keuangan'), (3, b'Produksi')], null=True)),
                ('push_notification_key', models.CharField(blank=True, default=b'', max_length=254)),
                ('is_staff', models.BooleanField(default=False, verbose_name=b'staff status')),
                ('is_active', models.BooleanField(default=True, verbose_name=b'aktif')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'Tanggal Terdaftar')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', overtime.apps.users.models.CustomUserManager()),
            ],
        ),
    ]
