# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-13 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_been_activated',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'Tekmas'), (2, b'Keuangan'), (3, b'Produksi')], null=True),
        ),
    ]
