# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-03-03 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('users', '0002_auto_20170614_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unit_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='departments.Department'),
        ),
    ]
