# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-01 07:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Overtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, b'Pengajuan'), (2, b'Disetujui Koodrinator'), (3, b'Disetujui Manager'), (4, b'Batal')], default=1)),
                ('notes_coordinator', models.TextField(blank=True, null=True, verbose_name=b'Catatan Koordinator')),
                ('notes_manager', models.TextField(blank=True, null=True, verbose_name=b'Catatan Manager')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtimes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
